# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import yolo_pb2 as yolo__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in yolo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class YoloInferenceStub(object):
    """YOLO 推理服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/yolo.YoloInference/Infer',
                request_serializer=yolo__pb2.InferRequest.SerializeToString,
                response_deserializer=yolo__pb2.DetectionResult.FromString,
                _registered_method=True)
        self.InferRaw = channel.unary_unary(
                '/yolo.YoloInference/InferRaw',
                request_serializer=yolo__pb2.ImageData.SerializeToString,
                response_deserializer=yolo__pb2.DetectionResult.FromString,
                _registered_method=True)
        self.InferStream = channel.stream_stream(
                '/yolo.YoloInference/InferStream',
                request_serializer=yolo__pb2.InferRequest.SerializeToString,
                response_deserializer=yolo__pb2.DetectionResult.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/yolo.YoloInference/Health',
                request_serializer=yolo__pb2.HealthRequest.SerializeToString,
                response_deserializer=yolo__pb2.HealthResponse.FromString,
                _registered_method=True)


class YoloInferenceServicer(object):
    """YOLO 推理服务
    """

    def Infer(self, request, context):
        """方案 A: Shared Memory 方式 (推荐)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InferRaw(self, request, context):
        """方案 B: 直接传数据 (保留兼容)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InferStream(self, request_iterator, context):
        """流式推理
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YoloInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=yolo__pb2.InferRequest.FromString,
                    response_serializer=yolo__pb2.DetectionResult.SerializeToString,
            ),
            'InferRaw': grpc.unary_unary_rpc_method_handler(
                    servicer.InferRaw,
                    request_deserializer=yolo__pb2.ImageData.FromString,
                    response_serializer=yolo__pb2.DetectionResult.SerializeToString,
            ),
            'InferStream': grpc.stream_stream_rpc_method_handler(
                    servicer.InferStream,
                    request_deserializer=yolo__pb2.InferRequest.FromString,
                    response_serializer=yolo__pb2.DetectionResult.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=yolo__pb2.HealthRequest.FromString,
                    response_serializer=yolo__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yolo.YoloInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yolo.YoloInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class YoloInference(object):
    """YOLO 推理服务
    """

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yolo.YoloInference/Infer',
            yolo__pb2.InferRequest.SerializeToString,
            yolo__pb2.DetectionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InferRaw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yolo.YoloInference/InferRaw',
            yolo__pb2.ImageData.SerializeToString,
            yolo__pb2.DetectionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InferStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/yolo.YoloInference/InferStream',
            yolo__pb2.InferRequest.SerializeToString,
            yolo__pb2.DetectionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yolo.YoloInference/Health',
            yolo__pb2.HealthRequest.SerializeToString,
            yolo__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
